name = "ask-cloudflare-svelte"
main = "./worker/index.js"
workers_dev = true
compatibility_date = "2026-01-01"

[[d1_databases]]
binding = "DATABASE"
database_id = "YOUR_D1_DATABASE_ID"

[build]
command = "npm install && npm run build"

[vars]
DATABASE_URL = ""
