name = "ask-cloudflare-svelte"
main = "./worker/index.js"
workers_dev = true
compatibility_date = "2026-01-01"

[[d1_databases]]
binding = "DATABASE"
database_name = "ask-db"
database_id = "be7f803f-9df5-4e53-80cb-193f544d26aa" # ask-db

[build]
command = "npm install && npm run build"

[vars]
DATABASE_URL = ""
